server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
