server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always

  metrics:
    export:
      prometheus:
        enabled: true
      cloudwatch:
        enabled: true
        namespace: SpringToCloudWatch
        batchSize: 10

cloud:
  aws:
    stack:
      auto: false

logging:
  level:
    io:
      micrometer: DEBUG
    org:
      springframework:
        web: WARN
        cloud: DEBUG
