server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always

  metrics:
    export:
      prometheus:
        enabled: true
      cloudwatch:
        enabled: true
        namespace: SpringToCloudWatch
        batchSize: 10

cloud:
  aws:
    stack:
      auto: false
    credentials:
      use-default-aws-credentials-chain: false

spring:
  jmx:
    enabled: true

logging:
  level:
    io:
      micrometer: DEBUG
    org:
      springframework:
        web: DEBUG
        cloud: DEBUG
        boot: DEBUG
    software:
      awssdk: DEBUG
    com:
      amazonaws: DEBUG
